version: '3.5'

services:
  api:
    container_name: api_container
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5020:80"
    networks:
      - api-net
    restart: unless-stopped

networks:
  api-net:
    driver: bridge
