# fly.toml app configuration file generated for crowdlaunch-backend on 2023-08-09T13:01:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crowdlaunch-backend"
primary_region = "lhr"

[build]

[env]
  DB_PASSWORD = "iBpY5H8w8M4MzBP"
  JWT_KEY = "Thisisaverylongkey2432fgnfnd5ytrjgrg544gns"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
