global using Xunit;
global using  Microsoft.AspNetCore.Mvc;
global using  MARKETPLACEAPI.Models;
global using MARKETPLACEAPI.Controllers;
global using  MARKETPLACEAPI.Interfaces;
global using  MARKETPLACEAPI.dto;
global using  FakeItEasy;
global using FluentAssertions;
global using AutoMapper;
